# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\flame_ws\open-link-tool\resource\ui\FirmwareUpgradeInterface.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FirmwareUpgradeInterface(object):
    def setupUi(self, FirmwareUpgradeInterface):
        FirmwareUpgradeInterface.setObjectName("FirmwareUpgradeInterface")
        FirmwareUpgradeInterface.resize(867, 781)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(FirmwareUpgradeInterface)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(24)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.treeWidget = TreeWidget(FirmwareUpgradeInterface)
        self.treeWidget.setObjectName("treeWidget")
        self.treeWidget.headerItem().setText(0, "1")
        self.horizontalLayout_2.addWidget(self.treeWidget)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(FirmwareUpgradeInterface)
        QtCore.QMetaObject.connectSlotsByName(FirmwareUpgradeInterface)

    def retranslateUi(self, FirmwareUpgradeInterface):
        _translate = QtCore.QCoreApplication.translate
        FirmwareUpgradeInterface.setWindowTitle(_translate("FirmwareUpgradeInterface", "Form"))
from qfluentwidgets import TreeWidget
